// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqOAJ34eiv24n06-XGEZLUAdZHHP1Xg00',
    appId: '1:36568930868:web:1e7715b6b3afddc6ba8861',
    messagingSenderId: '36568930868',
    projectId: 'todo-app-c10ae',
    authDomain: 'todo-app-c10ae.firebaseapp.com',
    storageBucket: 'todo-app-c10ae.appspot.com',
    measurementId: 'G-961FMFFKH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUosEC693EPEduvmwEvMNj4a21_GteFD4',
    appId: '1:36568930868:android:8eaf34f4795e3faaba8861',
    messagingSenderId: '36568930868',
    projectId: 'todo-app-c10ae',
    storageBucket: 'todo-app-c10ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjqNW62XpMAtViQrnfmyxizUe1bbX_ps',
    appId: '1:36568930868:ios:9cc46907b907b74fba8861',
    messagingSenderId: '36568930868',
    projectId: 'todo-app-c10ae',
    storageBucket: 'todo-app-c10ae.appspot.com',
    iosBundleId: 'com.example.todoAppv',
  );

}